dockerbeat.go
etc/dockerbeat.template.json

Add a memory percentage to the memory stats.
Closes #1

Memory stats

---

config.go
cpucalculator.go
dockerbeat.go
networkcalculator.go

Add some comments & executed a go fmt (clean up code)
Closes #10

Add comments & go fmt

---

Makefile

This new target allows to build dockerbeat in a golang container.

Add dockermake target

---

Dockerfile
README.md
etc/dockerbeat-docker.yml

Allowing a trusted build on docker hub. Following the #15 PR

Provide a dockerfile that build and execute the app

---

README.md
etc/dockerbeat.template.json
eventgenerator.go

@erwanncloarec Can you test to valid this PR?

Release 1.0.0-beta1

---

.gitignore
doc/fields.asciidoc
etc/dockerbeat.template.json
etc/fields.yml
scripts/generate_field_docs.py
scripts/generate_template.py

Add python scripts to generate asciidoc and template.
I also pushed generated files :)
It closes #23 #32 #31

Doc & template scripts

---

doc/fields.asciidoc
scripts/generate_field_docs.py

update generated asciidoc script to match with new sections

---

doc/fields.asciidoc
etc/fields.yml
eventgenerator.go
eventgenerator_test.go

Dockerbeat now generates a containerName

---

blkiocalculator.go
blkiocalculator_test.go
dockerbeat.go
etc/fields.yml
eventgenerator.go
eventgenerator_test.go

Closes #19 
I have to do the same as network stats to store the latest data and send the diff, not the raw value.

Add simple blkio read/write/total stats

---

dockerbeat.go

Use channel to receive ticker event or libbeat stop event to improve shut down performance. 
Ref - 
https://github.com/elastic/topbeat/commit/02ddbb07d638e47b4e06f42168aab061a11a63de
https://github.com/elastic/topbeat/commit/3f2bfd360f323d14e0e2af78564e331e228c4c47

Adopt time.Ticker() to perform fast shut down

---

cpucalculator.go
cpucalculator_test.go

Percentage numbers between 0 and 1

---

main.go

Ref - https://github.com/elastic/topbeat/pull/96

Exit on config error

---

doc/fields.asciidoc
etc/dockerbeat.template.json
scripts/generate_field_docs.py

@erwanncloarec as you can see, you have to update de `scripts/generate_fields_doc.py` file and add the new section.

Update doc and template (following to blkio update)

---

CONTRIBUTING.md
Makefile
README.md
beat/Dockerbeat_test.go
beat/EventGenerator_test.go

Write contributing file and update makefile / README

---

beat/Dockerbeat.go

This PR contains bugfix about #61 related to #60

Manage error when an error occurred with Docker API

---

beat/EventGenerator.go
beat/EventGenerator_test.go

adding a sanitized method (resolve #64)

Sanitize label names

---

beat/Dockerbeat.go

Update minimal version to 1.9

---

beat/EventGenerator.go
beat/EventGenerator_test.go

When no port, set empty array of port

---

README.md
beat/Dockerbeat.go
beat/Dockerbeat_test.go
beat/EventGenerator.go
beat/EventGenerator_test.go
doc/fields.asciidoc
etc/fields.yml

New field addition: docketSocket. This field is common to all types.
It refers to the #58 issue

New dockerSocket field

---

README.md
beat/Dockerbeat.go
beat/EventGenerator.go
beat/EventGenerator_test.go
doc/fields.asciidoc
etc/dockerbeat.template.json
etc/fields.yml
scripts/generate_field_docs.py

Done:
* documentation of a new type `log`
* develop new event type in the `EventGenerator` type to generate Log events
* use this new method in Dockerbeat to publish some Log events when an error occurred in the main loop
It is related to issue #62

Dockerbeat sends logging for error event to elasticsearch

---

etc/dockerbeat.service

Added file to run dockerbeat as systemd service.

Added service file for systemd.

---

README.md
beat/Config.go
beat/Dockerbeat.go
beat/Dockerbeat_test.go
etc/dockerbeat-docker.yml
etc/dockerbeat.yml

Add TLS feature to Dockerbeat:
* add new field tls in the configuration file
* update README
* implement TLS for Dockerbeat

TLS compatibility

---

beat/Dockerbeat.go
beat/Dockerbeat_test.go
beat/EventGenerator.go
beat/EventGenerator_test.go

Here is another proposal to resolve the concurrent map writes bug (see #90).
@TheStigger : can you compile and run this version and see if it resolves the bug?
Thx

Another proposal resolving concurrent map writes

---

beater/dockerbeat.go
beater/dockerbeat_test.go
config/config.go
dockerbeat.yml
etc/beat.yml
event/generator_test.go

implement enable/disable stat

---

beater/dockerbeat.go
config/config.go
event/generator.go
event/generator_test.go

Broken logging
